### ISSUE TITLE
项目download下来运行就报错，节点编辑保存也失败，没有效果

### ISSUE THREAD

**Issue by CZRZEISHUAI** [xinxin93/logicflow_vue_demo#2]
`Property or method "$_catTurboData" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <LF> at src/components/LF.vue
       <App> at src/App.vue
         <Root>`

**Comment by xinxin93** [comment]
调试代码忘记删除了，已修复
